AWSTemplateFormatVersion: 2010-09-09
Resources:
  SQLBackupToS3Role:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
    Path: /
  SQLBackupToS3InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref SQLBackupToS3Role
  SQLBackupToS3RolePolicies:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: SQLBackupToS3
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action: 
              - 's3:Get*'
              - 's3:List*'
              - 's3:Put*'
            Resource: 
              - 'arn:aws:s3:::iacflagstafftestbucket/*'
      Roles:
        - !Ref SQLBackupToS3Role
  